### ISSUE TITLE
Adicionar tempo de execução do programa

### ISSUE THREAD

**Issue by jwnx** [jwnx/lab-ic#7]

**Comment by RomanovV** [comment]
Eu não sei escrever um script mas o da pra fazer "$ time ./test.sh nameOfProgram.c" que ele deveolve o tempo de execução, não de cada execução mas do script como um todo, existe a opção de mostrar o tempe de execução de cada um, mas eu ainda não consegui fazer funcionar.

edit: Consegui colocar o runtime de cada execução
